### ISSUE TITLE
Graphique performance éditeurs

### ISSUE THREAD

**Issue by idris-maps** [nobrega1/ProjetDataVis#2]
Je n'ai pas compris exactement ce que tu essayes de montrer avec ton graphique. J'ai tenté de le mettre dans la page. ça affiche quelque chose mais probablement pas ce que tu avais l'intention de faire.

**Comment by JeanHerbaut** [comment]
Je pense qu'il y a du avoir un problème lorsque vous avez essayé car vendredi j'ai pu créer un graphe pour chaque année de 1976 à 2017 avec les ventes en millions des éditeurs. Je dois bien sûr encore le modifier mais le graphe était déjà disponible. Comment puis-je faire pour que vous le voyiez?

**Comment by idris-maps** [comment]
Je le vois mais il est un un peu bizarre. Au début il y a très peu d'éditeurs, ça va. Mais dès que tu arrive dans les années 2000 il y a tellement d'éditeurs que ça devient illisible. Probablement il faudrait faire une séléction. Ou faire un autre type de graphique, ou plusieurs graphiques, ça dépend ce que tu veux montrer. Si c'est pour montrer la performance dans le temps, je ferais juste un graphique avec une courbe par éditeur.

Quand tu change l'année, tu balances tout le graphique et le redessine à nouveau. Si tu utilises les transitions ça pourrait être animé. Regarde https://observablehq.com/@idris-maps/transitions-avec-d3
