### ISSUE TITLE
Graphique types de jeux

### ISSUE THREAD

**Issue by idris-maps** [nobrega1/ProjetDataVis#3]
J'ai mis en place le graphique radar avec les données d'exemples. Il faut que tu prépare tes données en fonction de ce que tu veux montrer. Tu peux créer un dossier dans `data` pour préparer les données, regarde comment j'ai fait pour les autres.

**Comment by LeonardMichiels** [comment]
Parfait merci, je vais y jeter un œil dans la semaine.
